version: '3.5'
services:
  pulsar-standalone:
    image: apachepulsar/pulsar:2.0.1-incubating
    ports:
    - 6650:6650
    - 8080:8080
    volumes:
    - pulsar-standalone-data:/pulsar/data
    command: bin/pulsar standalone

  # pulsar-standalone-dashboard:
  #   image: apachepulsar/pulsar-dashboard:2.0.1-incubating
  #   ports:
  #   - 8000:80
  #   environment:
  #     SERVICE_URL: http://pulsar-standalone:8080

volumes:
  pulsar-standalone-data:
