version: "3.6"

services:
  stan:
    image: nats-streaming:0.10.2-linux
    ports:
    - 4222:4222
    - 8222:8222
    command: --store file --dir /var/stan/datastore --max_channels 0 --max_subs 0 --max_msgs 0 --max_bytes 0 --max_age 0s
    volumes: 
    - stan-files:/var/stan/datastore

volumes:
  stan-files:

